/* eslint-disable max-lines */
const recipesMealsData = {
  meals: [
    {
      idMeal: '52977',
      strMeal: 'Corba',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Turkish',
      strInstructions: 'Pick through your  about a week.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
      strTags: 'Soup',
      strYoutube: 'https://www.youtube.com/watch?v=VVnZd8A84z4',
      strIngredient1: 'Lentils',
      strIngredient2: 'Onion',
      strIngredient3: 'Carrots',
      strIngredient4: 'Tomato Puree',
      strIngredient5: 'Cumin',
      strIngredient6: 'Paprika',
      strIngredient7: 'Mint',
      strIngredient8: 'Thyme',
      strIngredient9: 'Black Pepper',
      strIngredient10: 'Red Pepper Flakes',
      strIngredient11: 'Vegetable Stock',
      strIngredient12: 'Water',
      strIngredient13: 'Sea Salt',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 cup ',
      strMeasure2: '1 large',
      strMeasure3: '1 large',
      strMeasure4: '1 tbs',
      strMeasure5: '2 tsp',
      strMeasure6: '1 tsp ',
      strMeasure7: '1/2 tsp',
      strMeasure8: '1/2 tsp',
      strMeasure9: '1/4 tsp',
      strMeasure10: '1/4 tsp',
      strMeasure11: '4 cups ',
      strMeasure12: '1 cup ',
      strMeasure13: 'Pinch',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://findingtimeforcooking.com/main-dishes/red-lentil-soup-corba/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53060',
      strMeal: 'Burek',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Croatian',
      strInstructions: 'Fry the finely chopped serve.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/tkxquw1628771028.jpg',
      strTags: 'Streetfood, Onthego',
      strYoutube: 'https://www.youtube.com/watch?v=YsJXZwE5pdY',
      strIngredient1: 'Filo Pastry',
      strIngredient2: 'Minced Beef',
      strIngredient3: 'Onion',
      strIngredient4: 'Oil',
      strIngredient5: 'Salt',
      strIngredient6: 'Pepper',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 Packet',
      strMeasure2: '150g',
      strMeasure3: '150g',
      strMeasure4: '40g',
      strMeasure5: 'Dash',
      strMeasure6: 'Dash',
      strMeasure7: ' ',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.visit-croatia.co.uk/croatian-cuisine/croatian-recipes/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53065',
      strMeal: 'Sushi',
      strDrinkAlternate: null,
      strCategory: 'Seafood',
      strArea: 'Japanese',
      strInstructions: 'STEP 1TO MAKE SUSHI ROLLS: Pat out some rice.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=ub68OxEypaY',
      strIngredient1: 'Sushi Rice',
      strIngredient2: 'Rice wine',
      strIngredient3: 'Caster Sugar',
      strIngredient4: 'Mayonnaise',
      strIngredient5: 'Rice wine',
      strIngredient6: 'Soy Sauce',
      strIngredient7: 'Cucumber',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '300ml ',
      strMeasure2: '100ml',
      strMeasure3: '2 tbs',
      strMeasure4: '3 tbs',
      strMeasure5: '1 tbs',
      strMeasure6: '1 tbs',
      strMeasure7: '1',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://www.bbcgoodfood.com/recipes/simple-sushi',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52978',
      strMeal: 'Kumpir',
      strDrinkAlternate: null,
      strCategory: 'Side',
      strArea: 'Turkish',
      strInstructions: 'If you order kumpir in Turkey.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/mlchx21564916997.jpg',
      strTags: 'SideDish',
      strYoutube: 'https://www.youtube.com/watch?v=IEDEtZ4UVtI',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Butter',
      strIngredient3: 'Cheese',
      strIngredient4: 'Onion',
      strIngredient5: 'Red Pepper',
      strIngredient6: 'Red Chile Flakes',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 large',
      strMeasure2: '2 tbs',
      strMeasure3: '150g',
      strMeasure4: '1 large',
      strMeasure5: '1 large',
      strMeasure6: 'Pinch',
      strMeasure7: ' ',
      strMeasure8: ' ',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'http://www.turkeysforlife.com/2013/10/firinda-kumpir-turkish-street-food.html',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53026',
      strMeal: 'Tamiya',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Egyptian',
      strInstructions: 'oak the beans in water to cover overnight.Drain.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/n3xxd91598732796.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=mulqW-J3Yy4',
      strIngredient1: 'Broad Beans',
      strIngredient2: 'Spring Onions',
      strIngredient3: 'Garlic Clove',
      strIngredient4: 'Parsley',
      strIngredient5: 'Cumin',
      strIngredient6: 'Baking Powder',
      strIngredient7: 'Cayenne Pepper',
      strIngredient8: 'Flour',
      strIngredient9: 'Vegetable Oil',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '3 cups ',
      strMeasure2: '6',
      strMeasure3: '4',
      strMeasure4: '1/4 cup',
      strMeasure5: '2 tsp',
      strMeasure6: '1 tsp ',
      strMeasure7: '1/2 tsp',
      strMeasure8: 'Spinkling',
      strMeasure9: 'As required',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://oukosher.org/recipes/tamiya-egyptian-dried-fava-bean-fritters/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '53069',
      strMeal: 'Bistek',
      strDrinkAlternate: null,
      strCategory: 'Beef',
      strArea: 'Filipino',
      strInstructions: '0.Marinate beef in soy sauce, lemon (or calamansi).',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/4pqimk1683207418.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=xOQON5_S7as',
      strIngredient1: 'Beef',
      strIngredient2: 'Soy Sauce',
      strIngredient3: 'Lemon',
      strIngredient4: 'Garlic',
      strIngredient5: 'Onion',
      strIngredient6: 'Olive Oil',
      strIngredient7: 'Water',
      strIngredient8: 'Salt',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 lb',
      strMeasure2: '5 tablespoons',
      strMeasure3: '1',
      strMeasure4: '3 cloves',
      strMeasure5: '3 parts ',
      strMeasure6: '4 tbs',
      strMeasure7: '1 cup ',
      strMeasure8: '1 pinch',
      strMeasure9: ' ',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'https://panlasangpinoy.com/bistek-tagalog-beefsteak-recipe/',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52785',
      strMeal: 'Dal fry',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Indian',
      strInstructions: 'Wash and soak toor dal in approx.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wuxrtu1483564410.jpg',
      strTags: 'Curry,Vegetarian,Cake',
      strYoutube: 'https://www.youtube.com/watch?v=J4D855Q9-jg',
      strIngredient1: 'Toor dal',
      strIngredient2: 'Water',
      strIngredient3: 'Salt',
      strIngredient4: 'Turmeric',
      strIngredient5: 'Ghee',
      strIngredient6: 'Chopped tomatoes',
      strIngredient7: 'Cumin seeds',
      strIngredient8: 'Mustard Seeds',
      strIngredient9: 'Bay Leaf',
      strIngredient10: 'Green Chili',
      strIngredient11: 'Ginger',
      strIngredient12: 'Cilantro',
      strIngredient13: 'Red Pepper',
      strIngredient14: 'Salt',
      strIngredient15: 'Sugar',
      strIngredient16: 'Garam Masala',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 cup',
      strMeasure2: '2-1/2 cups',
      strMeasure3: '1 tsp',
      strMeasure4: '1/4 tsp',
      strMeasure5: '3 tbs',
      strMeasure6: '1 cup',
      strMeasure7: '1/2 tsp',
      strMeasure8: '1/2 tsp',
      strMeasure9: '2',
      strMeasure10: '1 tbs chopped',
      strMeasure11: '2 tsp shredded',
      strMeasure12: '2 tbs ',
      strMeasure13: '1/2 tsp',
      strMeasure14: '1/2 tsp',
      strMeasure15: '1 tsp',
      strMeasure16: '1/4 tsp',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.instagram.com/p/BO21bpYD3Fu',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52804',
      strMeal: 'Poutine',
      strDrinkAlternate: null,
      strCategory: 'Miscellaneous',
      strArea: 'Canadian',
      strInstructions: 'Heat oil in a deep fryer or deep heavy skillet.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuyrrx1487327597.jpg',
      strTags: 'UnHealthy,Speciality,HangoverFood',
      strYoutube: 'https://www.youtube.com/watch?v=UVAMAoA2_WU',
      strIngredient1: 'Vegetable Oil',
      strIngredient2: 'Beef Gravy',
      strIngredient3: 'Potatoes',
      strIngredient4: 'Cheese Curds',
      strIngredient5: '',
      strIngredient6: '',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: 'Dash',
      strMeasure2: '1 Can',
      strMeasure3: '5 thin cut',
      strMeasure4: '2 cups',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.food.com/recipe/real-canadian-poutine-113388',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52844',
      strMeal: 'Lasagne',
      strDrinkAlternate: null,
      strCategory: 'Pasta',
      strArea: 'Italian',
      strInstructions: 'Heat the oil in a large saucepan.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wtsvxx1511296896.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=gfhfsBPt46s',
      strIngredient1: 'Olive Oil',
      strIngredient2: 'Bacon',
      strIngredient3: 'Onion',
      strIngredient4: 'Celery',
      strIngredient5: 'Carrots',
      strIngredient6: 'Garlic',
      strIngredient7: 'Minced Beef',
      strIngredient8: 'Tomato Puree',
      strIngredient9: 'Chopped Tomatoes',
      strIngredient10: 'Honey',
      strIngredient11: 'Lasagne Sheets',
      strIngredient12: 'Creme Fraiche',
      strIngredient13: 'Mozzarella Balls',
      strIngredient14: 'Parmesan Cheese',
      strIngredient15: 'Basil Leaves',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1 tblsp ',
      strMeasure2: '2',
      strMeasure3: '1 finely chopped ',
      strMeasure4: '1 Stick',
      strMeasure5: '1 medium',
      strMeasure6: '2 cloves chopped',
      strMeasure7: '500g',
      strMeasure8: '1 tbls',
      strMeasure9: '800g',
      strMeasure10: '1 tblsp ',
      strMeasure11: '500g',
      strMeasure12: '400ml',
      strMeasure13: '125g',
      strMeasure14: '50g',
      strMeasure15: 'Topping',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'https://www.bbcgoodfood.com/recipes/classic-lasagne',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52929',
      strMeal: 'Timbits',
      strDrinkAlternate: null,
      strCategory: 'Dessert',
      strArea: 'Canadian',
      strInstructions: 'Sift together dry ingredients.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/txsupu1511815755.jpg',
      strTags: 'Snack,Treat',
      strYoutube: 'https://www.youtube.com/watch?v=fFLn1h80AGQ',
      strIngredient1: 'Flour',
      strIngredient2: 'Sugar',
      strIngredient3: 'Baking Powder',
      strIngredient4: 'Salt',
      strIngredient5: 'Egg',
      strIngredient6: 'Milk',
      strIngredient7: 'Oil',
      strIngredient8: 'Oil',
      strIngredient9: 'Icing Sugar',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '2 cups ',
      strMeasure2: '1/3 cup',
      strMeasure3: '3 tsp',
      strMeasure4: 'tsp',
      strMeasure5: '1 beaten',
      strMeasure6: 'cup',
      strMeasure7: '3 tbs',
      strMeasure8: 'for frying',
      strMeasure9: 'garnish',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.geniuskitchen.com/recipe/drop-doughnuts-133877',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52948',
      strMeal: 'Wontons',
      strDrinkAlternate: null,
      strCategory: 'Pork',
      strArea: 'Chinese',
      strInstructions: 'Combine pork, garlic, ginger, soy sauce, sesame oil.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1525876468.jpg',
      strTags: 'MainMeal',
      strYoutube: 'https://www.youtube.com/watch?v=9h9No18ZyCI',
      strIngredient1: 'Pork',
      strIngredient2: 'Garlic Clove',
      strIngredient3: 'Ginger',
      strIngredient4: 'Soy Sauce',
      strIngredient5: 'Sesame Seed Oil',
      strIngredient6: 'Carrots',
      strIngredient7: 'Celery',
      strIngredient8: 'Spring Onions',
      strIngredient9: 'Wonton Skin',
      strIngredient10: 'Oil',
      strIngredient11: 'Water',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '1lb',
      strMeasure2: '3 chopped',
      strMeasure3: '1 tsp ',
      strMeasure4: '1 tbs',
      strMeasure5: '1 tsp ',
      strMeasure6: '3 finely chopped',
      strMeasure7: '3 finely chopped',
      strMeasure8: '6 chopped',
      strMeasure9: '1 Packet',
      strMeasure10: 'Fry',
      strMeasure11: 'Bottle',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strMeasure16: '',
      strMeasure17: '',
      strMeasure18: '',
      strMeasure19: '',
      strMeasure20: '',
      strSource: 'http://www.geniuskitchen.com/recipe/chinese-wontons-20235',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
    {
      idMeal: '52971',
      strMeal: 'Kafteji',
      strDrinkAlternate: null,
      strCategory: 'Vegetarian',
      strArea: 'Tunisian',
      strInstructions: 'Peel potatoes and cut into 5cm cubes.',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1bsv1q1560459826.jpg',
      strTags: null,
      strYoutube: 'https://www.youtube.com/watch?v=-TFf-Zu-xQU',
      strIngredient1: 'Potatoes',
      strIngredient2: 'Olive Oil',
      strIngredient3: 'Green Pepper',
      strIngredient4: 'Onions',
      strIngredient5: 'Ras el hanout',
      strIngredient6: 'Pumpkin',
      strIngredient7: 'Eggs',
      strIngredient8: 'Salt',
      strIngredient9: 'Pepper',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strIngredient16: '',
      strIngredient17: '',
      strIngredient18: '',
      strIngredient19: '',
      strIngredient20: '',
      strMeasure1: '5 Large',
      strMeasure2: '2 tbs',
      strMeasure3: '1',
      strMeasure4: '5',
      strMeasure5: '1 tbs',
      strMeasure6: '500g',
      strMeasure7: '24 Skinned',
      strMeasure8: 'Pinch',
      strMeasure9: 'Pinch',
      strMeasure10: ' ',
      strMeasure11: ' ',
      strMeasure12: ' ',
      strMeasure13: ' ',
      strMeasure14: ' ',
      strMeasure15: ' ',
      strMeasure16: ' ',
      strMeasure17: ' ',
      strMeasure18: ' ',
      strMeasure19: ' ',
      strMeasure20: ' ',
      strSource: 'http://allrecipes.co.uk/recipe/12294/kafteji--tunisian-fried-vegetables-.aspx',
      strImageSource: null,
      strCreativeCommonsConfirmed: null,
      dateModified: null,
    },
  ],
};

const categoryMealsData = {
  meals: [
    { strCategory: 'Beef' },
    { strCategory: 'Breakfast' },
    { strCategory: 'Chicken' },
    { strCategory: 'Dessert' },
    { strCategory: 'Goat' },
    { strCategory: 'Lamb' },
  ],
};

const categoryData = {
  meals: [
    {
      strMeal: 'Beef and Mustard Pie',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sytuqu1511553755.jpg',
      idMeal: '52874',
    },
    {
      strMeal: 'Beef and Oyster pie',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wrssvt1511556563.jpg',
      idMeal: '52878',
    },
    {
      strMeal: 'Beef Asado',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/pkopc31683207947.jpg',
      idMeal: '53071',
    },
    {
      strMeal: 'Beef Banh Mi Bowls with Sriracha Mayo, Carrot & Pickled Cucumber',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/z0ageb1583189517.jpg',
      idMeal: '52997',
    },
    {
      strMeal: 'Beef Bourguignon',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/vtqxtu1511784197.jpg',
      idMeal: '52904',
    },
    {
      strMeal: 'Beef Brisket Pot Roast',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ursuup1487348423.jpg',
      idMeal: '52812',
    },
    {
      strMeal: 'Beef Caldereta',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/41cxjh1683207682.jpg',
      idMeal: '53070',
    },
    {
      strMeal: 'Beef Dumpling Stew',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uyqrrv1511553350.jpg',
      idMeal: '52873',
    },
    {
      strMeal: 'Beef Lo Mein',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1529444830.jpg',
      idMeal: '52952',
    },
    {
      strMeal: 'Beef Mechado',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/cgl60b1683206581.jpg',
      idMeal: '53068',
    },
    {
      strMeal: 'Beef Rendang',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/bc8v651619789840.jpg',
      idMeal: '53053',
    },
    {
      strMeal: 'Beef stroganoff',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/svprys1511176755.jpg',
      idMeal: '52834',
    },
    {
      strMeal: 'Beef Sunday Roast',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ssrrrs1503664277.jpg',
      idMeal: '52824',
    },
    {
      strMeal: 'Beef Wellington',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/vvpprx1487325699.jpg',
      idMeal: '52803',
    },
    {
      strMeal: 'Big Mac',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/urzj1d1587670726.jpg',
      idMeal: '53013',
    },
    {
      strMeal: 'Bistek',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/4pqimk1683207418.jpg',
      idMeal: '53069',
    },
    {
      strMeal: 'Bitterballen (Dutch meatballs)',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/lhqev81565090111.jpg',
      idMeal: '52979',
    },
    {
      strMeal: 'Braised Beef Chilli',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uuqvwu1504629254.jpg',
      idMeal: '52826',
    },
    {
      strMeal: 'Cevapi Sausages',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/vc08jn1628769553.jpg',
      idMeal: '53055',
    },
    {
      strMeal: 'Chivito uruguayo',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/n7qnkb1630444129.jpg',
      idMeal: '53063',
    },
    {
      strMeal: 'Corned Beef and Cabbage',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/xb97a81583266727.jpg',
      idMeal: '52998',
    },
    {
      strMeal: 'Croatian Bean Stew',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/tnwy8m1628770384.jpg',
      idMeal: '53058',
    },
    {
      strMeal: 'Croatian lamb peka',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/pn59o51628769837.jpg',
      idMeal: '53056',
    },
    {
      strMeal: 'Egyptian Fatteh',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/rlwcc51598734603.jpg',
      idMeal: '53031',
    },
    {
      strMeal: 'Gołąbki (cabbage roll)',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/q8sp3j1593349686.jpg',
      idMeal: '53021',
    },
    {
      strMeal: 'Irish stew',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sxxpst1468569714.jpg',
      idMeal: '52781',
    },
    {
      strMeal: 'Jamaican Beef Patties',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/wsqqsw1515364068.jpg',
      idMeal: '52938',
    },
    {
      strMeal: 'Ma Po Tofu',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1525874812.jpg',
      idMeal: '52947',
    },
    {
      strMeal: 'Massaman Beef curry',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/tvttqv1504640475.jpg',
      idMeal: '52827',
    },
    {
      strMeal: 'Minced Beef Pie',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/xwutvy1511555540.jpg',
      idMeal: '52876',
    },
    {
      strMeal: 'Montreal Smoked Meat',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/uttupv1511815050.jpg',
      idMeal: '52927',
    },
    {
      strMeal: 'Moussaka',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ctg8jd1585563097.jpg',
      idMeal: '53006',
    },
    {
      strMeal: 'Mulukhiyah',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/x372ug1598733932.jpg',
      idMeal: '53029',
    },
    {
      strMeal: 'Oxtail with broad beans',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1520083578.jpg',
      idMeal: '52943',
    },
    {
      strMeal: 'Paszteciki (Polish Pasties)',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/c9a3l31593261890.jpg',
      idMeal: '53017',
    },
    {
      strMeal: 'Pate Chinois',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/yyrrxr1511816289.jpg',
      idMeal: '52930',
    },
    {
      strMeal: 'Portuguese prego with green piri-piri',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/ewcikl1614348364.jpg',
      idMeal: '53042',
    },
    {
      strMeal: 'Red Peas Soup',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sqpqtp1515365614.jpg',
      idMeal: '52941',
    },
    {
      strMeal: 'Roti john',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/hx335q1619789561.jpg',
      idMeal: '53052',
    },
    {
      strMeal: 'Soy-Glazed Meatloaves with Wasabi Mashed Potatoes & Roasted Carrots',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/o2wb6p1581005243.jpg',
      idMeal: '52992',
    },
    {
      strMeal: 'Spaghetti Bolognese',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg',
      idMeal: '52770',
    },
    {
      strMeal: 'Steak and Kidney Pie',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/qysyss1511558054.jpg',
      idMeal: '52881',
    },
    {
      strMeal: 'Steak Diane',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/vussxq1511882648.jpg',
      idMeal: '52935',
    },
    {
      strMeal: 'Szechuan Beef',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/1529443236.jpg',
      idMeal: '52950',
    },
    {
      strMeal: 'Traditional Croatian Goulash',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/n1hcou1628770088.jpg',
      idMeal: '53057',
    },
    {
      strMeal: 'Vegetable Shepherd\'s Pie',
      strMealThumb: 'https://www.themealdb.com/images/media/meals/w8umt11583268117.jpg',
      idMeal: '53000',
    },
  ],
};

export {
  recipesMealsData,
  categoryMealsData,
  categoryData,
};
